### ISSUE TITLE
Form validation styling is broken

### ISSUE THREAD

**Issue by Katrienvh** [sumocoders/forkcms#132]
## Type

- Critical bug

## Problem description

Bootstrap4 now uses the class .is-invalid on the input field to add validation styling. The field is render with `{{ field.html|raw }}` so i can't add an option with the class on it to show the error styling when needed. Before the class stands on the `.form-group` class so we could add is easily

https://getbootstrap.com/docs/4.0/components/forms/#validation

**Comment by carakas** [comment]
@Katrienvh wouldn't it be better to also add this fix already to fork?  So that if others want to use BS4 they don't run into the same issue?

**Comment by Katrienvh** [comment]
But fork is BS3 and the form errors are different there, the error classes stand on the form group around the label and the input field, in BS4 the error class stands on the input field itself

**Comment by carakas** [comment]
but it won't hurt if we add it right?

**Comment by Katrienvh** [comment]
ooh ok like that, i don't think i will break the error styling of BS3 if you add the classes on the input field for the error styling of BS4.

**Comment by carakas** [comment]
we'll do this with css for now, and add it as a feature in fork 5.1
